routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('start-chat');
});

Route::post('/', 'CustomerServiceController@store');

Route::get('/offline',function () {
    return view('offline');
});

// Route::group(['middleware' => ['web']], function () {
//     Route::post('/customer-service', 'CustomerServiceController@store');
// });

Auth::routes();

// Route::get('/user', 'HomeController@user')->name('user');
Route::group(['middleware' => ['auth']], function () {
    // Route::get('/users', 'UserController@index')->name('user');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('users', 'UserController');
    Route::get('/users-set-status/{id}', 'UserController@setStatus')->name('set.status');
    Route::get('/users-set-schedule/{id}', 'UserController@setSchedule')->name('set.schedule');
    Route::get('/users-delete-schedule/{id}', 'UserController@deleteSchedule')->name('delete.schedule');
    Route::get('/users-restore-schedule/{id}', 'UserController@restoreSchedule')->name('restore.schedule');
    Route::post('/users-post-schedule/{id}', 'UserController@setPostSchedule')->name('post.schedule');

});

Route::get('/customer-service', 'HomeController@cs')->name('customer.service');

app/User.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use EloquentFilter\Filterable;

class User extends Authenticatable
{
    use Notifiable, SoftDeletes, Filterable;

    protected static function boot()
    {
        parent::boot();

        static::creating(function ($model) {
            $model->is_maid = 0;
            $model->is_available = 0;
            $model->count_servicing = 0;
            $model->password = bcrypt('password');
        });
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'phone',
        'password',
        'count_servicing',
        'is_maid',
        'is_available',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function modelFilter()
    {
        return $this->provideFilter(\App\ModelFilters\UserFilter::class);
    }

    public function inServiceToday()
    {
        return $this->hasOne(CustomerService::class, 'customer_id', 'id')->whereDate('created_at', Carbon::today());
    }

    public function inServices()
    {
        return $this->belongsTo(CustomerService::class, 'service_id', 'id');
    }

    public function history()
    {
        return $this->belongsTo(CustomerService::class, 'service_id', 'id');
    }

    public function schedules()
    {
        return $this->hasMany('App\Schedule', 'user_id');
    }

    public function allSchedules()
    {
        return $this->hasMany('App\Schedule', 'user_id')->withTrashed();
    }

    public function countServer()
    {
        return $this->whereIsMaid(1)->count();
    }

    public function countCustomer()
    {
        return $this->whereIsMaid(0)->count();
    }

    public function startServicer()
    {
        // reset count servicing
        $this->where('count_servicing', '>', 0)->update(['count_servicing' => 0]);

        // ambil user yg online sekarang
        return $this->where([
            'is_maid' => 1,
            'is_available' => 1,
        ])->whereHas('schedules', function ($q) {
            return $q->where('day', date('w'))
                ->whereTime('start_at', '<=', date('H:i:s'))
                ->whereTime('end_at', '>=', date('H:i:s'));
        })->limit(1)->inRandomOrder()->get()->first();
    }

    public function nextServicer()
    {
        // reset count servicing
        // $this->where('is_available', 1)->update(['count_servicing' => 1]);

        // ambil user yg online sekarang
        return $this->where([
            'is_maid' => 1,
            'is_available' => 1,
        ])->whereHas('schedules', function ($q) {
            return $q->where('day', date('w'))
                ->whereTime('start_at', '<=', date('H:i:s'))
                ->whereTime('end_at', '>=', date('H:i:s'));
        })->limit(1)
        ->orderBy('count_servicing', 'asc')
        ->get()->first();
    }

    public function onWorkingHour()
    {
        return $this->whereHas('schedules', function ($q) {
            return $q->where('day', date('w'))
                ->whereTime('start_at', '<=', date('H:i:s'))
                ->whereTime('end_at', '>=', date('H:i:s'));
        })->first();
    }

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Schedule;
use App\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $users = User::filter($request->all())->with('schedules')->latest()->paginate(10);
        $users->appends([
            'search' => $request->search,
            'is_maid' => $request->is_maid
        ]);
        return view('page.users.index', ['users' => $users]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('page.users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $this->validateData($request);

        User::create($data);

        return redirect()->back()->with(['status', 'Success create user']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        dd($id, $request);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function setStatus(Request $request, $id)
    {
        $user = User::findOrFail($id);
        $user->update($request->all());
        return redirect()->back();
    }

    public function setSchedule($id)
    {
        $user = User::findOrFail($id);
        return view('page.users.set-schedule', [ 'user' => $user ]);
    }

    public function setPostSchedule(Request $request, $id)
    {
        $data = $this->validateData($request);

        $user = User::with('schedules')->findOrFail($id);
        $user->update($data);

        if ($request->day || $request->start_at || $request->end_at) {
            $schedule = $request->validate([
                'day' => 'required',
                'start_at' => 'required',
                'end_at' => 'required',
            ]);

            Schedule::updateOrCreate([
                'user_id' => $user->id,
                'day' => $schedule['day'],
            ],[
                'start_at' => $schedule['start_at'],
                'end_at' => $schedule['end_at'],
            ]);
        }

        return redirect()->back()->with(['status', 'Success create user']);

    }

    public function deleteSchedule($id)
    {
        Schedule::findOrFail($id)->delete();
        return redirect()->back()->with(['status', 'Success delete schedule']);
    }

    public function restoreSchedule($id)
    {
        Schedule::withTrashed()->findOrFail($id)->restore();
        return redirect()->back()->with(['status', 'Success restore schedule']);
    }

    private function validateData(Request $request)
    {
        return $request->validate([
            'name' => 'required',
            'email' => 'required|email',
            'phone' => 'required|numeric',
        ]);
    }

}

resources/views/page/users/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    Add Users
                    <a href="{{ route('users.create') }}" class="float-right btn btn-primary">Add</a>
                </div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <form action="{{ route('users.store') }}" method="post">
                        @csrf
                        <div class="form-group">
                            <label for="">Name</label>
                            <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" value="{{ old('name') }}">
                            @error('name')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="">Email</label>
                            <input type="email" name="email" class="form-control @error('email') is-invalid @enderror" value="{{ old('email') }}">
                            @error('email')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="">Phone</label>
                            <input type="number" name="phone" class="form-control @error('phone') is-invalid @enderror" value="{{ old('phone') }}">
                            @error('phone')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <button class="btn btn-primary float-right">Submit</button>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/page/users/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    Users
                    <a href="{{ route('users.create') }}" class="float-right btn btn-primary">Add</a>
                </div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <form action="" method="get">
                        <div class="row">
                            <div class="col-md-8 form-inline">
                                <div class="form-group">
                                    <select name="is_maid" id="" class="form-control">
                                        <option value=""> Is Admin </option>
                                        <option value="1" {{ request('is_maid') == '1' ? 'selected' : '' }} > Ya </option>
                                        <option value="0" {{ request('is_maid') == '0' ? 'selected' : '' }} > Tidak </option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <select name="is_available" id="" class="form-control">
                                        <option value=""> Is Available </option>
                                        <option value="1" {{ request('is_available') == '1' ? 'selected' : '' }} > Ya </option>
                                        <option value="0" {{ request('is_available') == '0' ? 'selected' : '' }} > Tidak </option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <select name="day" id="" class="form-control">
                                        <option value=""> Hari </option>
                                        @foreach([1,2,3,4,5,6,0] as $i)
                                            <option value="{{ $i }}" {{ request('day') == "$i" ? 'selected' : '' }} > {{ dayName($i) }} </option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <input type="text" class="form-control" name="search" placeholder="Pencarian" value="{{ request('search') }}">
                            </div>
                            <div class="col-md-1">
                                <button class="btn btn-primary">Filter</button>
                            </div>
                        </div>
                    </form>
                    <hr>
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Name / Email / Phone</th>
                                    <th>Schedule</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($users as $user)
                                    @include('page.users.child.row')
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    {{ $users->links() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/page/users/set-schedule.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
<form action="{{ route('post.schedule', $user->id) }}" method="POST">

    <div class="row justify-content-center">
        @if (session('status'))
            <div class="alert alert-success" role="alert">
                {{ session('status') }}
            </div>
        @endif

        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    Data User
                </div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif


                        @csrf
                        <div class="form-group">
                            <label for="">Name : </label>
                            <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" value="{{ isset($user->name) ? $user->name :  old('name') }}">
                            @error('name')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="">Email : </label>
                            <input type="email" name="email" class="form-control @error('email') is-invalid @enderror" value="{{ isset($user->email) ? $user->email : old('email') }}">
                            @error('email')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="">Phone : </label>
                            <input type="number" name="phone" class="form-control @error('phone') is-invalid @enderror" value="{{ isset($user->phone) ? $user->phone : old('phone') }}">
                            @error('phone')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <button class="btn btn-primary ">Update User</button>
                        </div>

                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    Set Schedule Users
                </div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <div class="form-group">
                        <label for="">Hari : </label>
                        <select name="day" id="" class="form-control">
                            <option value="1">Senin</option>
                            <option value="2">Selasa</option>
                            <option value="3">Rabu</option>
                            <option value="4">Kamis</option>
                            <option value="5">Jumat</option>
                            <option value="6">Sabtu</option>
                            <option value="0">Minggu</option>
                        </select>
                        @error('day')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="">Jam Mulai : </label>
                        <input type="time" name="start_at" class="form-control">
                        @error('start_at')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="">Jam Akhir : </label>
                        <input type="time" name="end_at" class="form-control">
                        @error('start_at')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                    <div class="form-group text-right">
                        <button class="btn btn-primary ">Save Schedule</button>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <div class="row mt-3">
        <div class="col-md-12">
             <div class="card">
                <div class="card-header">
                    Set Schedule Users
                </div>

                <div class="card-body">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>Hari</th>
                                <th>Jam Mulai</th>
                                <th>Jam Akhir</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if ($user->allSchedules->count() > 0)
                                @foreach ($user->allSchedules as $schedule)
                                    <tr>
                                        <td> {{ dayName($schedule->day) }} </td>
                                        <td> {{ $schedule->start_at }} </td>
                                        <td> {{ $schedule->end_at }} </td>
                                        <td>
                                            @if ($schedule->deleted_at)
                                                <a href="{{ route('restore.schedule', $schedule->id) }}" class="btn btn-warning btn-sm">Restore</a>
                                            @else
                                                <a href="{{ route('delete.schedule', $schedule->id) }}" class="btn btn-danger btn-sm">Delete</a>
                                            @endif
                                        </td>
                                    </tr>
                                @endforeach
                            @else

                            @endif
                        </tbody>
                    </table>
                </div>
             </div>

        </div>
    </div>
</form>

</div>
@endsection